language: android

jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=27
    - ANDROID_BUILD_TOOLS_VERSION=29.0.2

git:
  depth: 1

before_install:
  - yes | sdkmanager "platforms;android-27"

android:
  components:
    - tools
    - platform-tools
    - tools # Appears twice per Travis docs (to update the tools)
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
